### ISSUE TITLE
Refactor driver management

### ISSUE THREAD

**Issue by derdualist** [IBM/gauge-web-app-steps#4]
Selenium 4 introduced it's own driver management. It should replace the `webdriver-manager` dependency.

https://www.selenium.dev/blog/2022/introducing-selenium-manager/

* remove webdriver-manager from requirements.txt and setup.py
* refactor driver_factory.py
* check docs for references and update if needed

**Comment by mario-s** [comment]
Let's put this on hold till Selenium's driver manager is out of beta.
